### ISSUE TITLE
Put your project in the EnTT in Action list

### ISSUE THREAD

**Issue by skypjack** [bilek993/CLUSEK#1]
Hi, sorry to bother you, I'm the author of `EnTT`.

I found your project and I'd like to add it to the [list of showcases](https://github.com/skypjack/entt/wiki/EnTT-in-Action) for `EnTT`.
You can make a PR or just close the issue with a :+1: if you prefer, I'll add it for you.
What do you think about? My goal is to provide the users of `EnTT` with a few examples to give them inspiration and more when they take their first steps. It goes without saying that your project is definitely a good candidate! :)

**Comment by bilek993** [comment]
I'm sorry, but I'm not interested.
